name: update-podcast-feeds

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 5"

jobs:
  update-quiz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: ./scripts/sync.sh
