[package]
name = "kviss-db"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
reqwest = "0.12.4"
rusqlite = "0.31.0"
scraper = "0.19.0"
serde_json = "1.0.117"
tokio = { version = "1.38.0", features = ["full"] }
