name: update-latest-quiz

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 5"

jobs:
  update-quiz:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run script
        run: ./scripts/sync.sh

      - name: Check for changes
        id: check_changes
        run: |
          git diff --exit-code || echo "has_changes=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.has_changes == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "chore: update content"
          git push
